version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --s3-bucket 657672949295-aws-bucket1 --output-template-file packaged.yaml

artifacts:
  type: zip
  files:
    - packaged.yaml